# Generated by Django 5.1.3 on 2024-11-27 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('country', models.CharField(max_length=100, verbose_name='Pavardė')),
            ],
            options={
                'ordering': ['country', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(help_text='Įveskite automobilio kėbulo tipą (pvz. Hečbekas)', max_length=200, verbose_name='Kėbulo tipas')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(max_length=200, verbose_name='Modelis')),
                ('summary', models.TextField(help_text='Trumpas automobilio aprašymas', max_length=1000, verbose_name='Aprašymas')),
                ('vin', models.CharField(help_text='13 Simbolių <a href="https://lt.wikipedia.org/wiki/Automobilio_identifikacinis_kodas">VIN kodas</a>', max_length=13, verbose_name='VIN')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.brand')),
                ('types', models.ManyToManyField(help_text='Išrinkite kėbulo tipą', to='autoservice.types')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus ID automobilio kopijai', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Bus prieinama')),
                ('status', models.CharField(blank=True, choices=[('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima paimti'), ('r', 'Rezervuota')], default='a', help_text='Statusas', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
