# Generated by Django 5.1.3 on 2024-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Gamitojo šalis'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Gamintojas'),
        ),
    ]
